const configToExport = {
  MAX_ATTACHMENT_SIZE: 5000000,
  s3: {
    REGION: process.env.REACT_APP_S3_ATTACHMENTS_BUCKET_REGION,
    BUCKET: process.env.REACT_APP_S3_ATTACHMENTS_BUCKET_NAME,
  },
  apiGateway: {
    REGION: process.env.REACT_APP_API_REGION,
    URL: process.env.REACT_APP_API_URL,
  },
  cognito: {
    REGION: process.env.REACT_APP_COGNITO_REGION,
    USER_POOL_ID: process.env.REACT_APP_COGNITO_USER_POOL_ID,
    APP_CLIENT_ID: process.env.REACT_APP_COGNITO_USER_POOL_CLIENT_ID,
    APP_CLIENT_DOMAIN: process.env.REACT_APP_COGNITO_USER_POOL_CLIENT_DOMAIN,
    IDENTITY_POOL_ID: process.env.REACT_APP_COGNITO_IDENTITY_POOL_ID,
    REDIRECT_SIGNIN: process.env.REACT_APP_COGNITO_REDIRECT_SIGNIN,
    REDIRECT_SIGNOUT: process.env.REACT_APP_COGNITO_REDIRECT_SIGNOUT,
  },
};

export default configToExport;
