
title: CDK Webapp
description: A template for a serverless, cloud native, form submission application.
# baseurl: "/docs" # the subpath of your site, e.g. /blog
# url: "https://just-the-docs.github.io" # the base hostname & protocol for your site, e.g. http://example.com

repo:
  org: stratiformdigital
  name: cdk-webapp
  url: https://github.com/stratiformdigital/cdk-webapp

team:
  members: # This list automatically populates the Team Introduction page.  Add/Edit as appropriate.
    - role: Product Owner
      description: Responsible for project scope, direction, and delivery.
      name: Mike Dial
      email: mike.dial@stratiform.digital
  core_hours: 10:00am - 3:00pm ET

meetings:
  - name: Daily Standup
    time: 10:00am - 10:30am ET
    attendance: optional
    link: None (TBD)

aws: 
  login_url: https://stratiformdigital.awsapps.com/start

contact_email: mike.dial@stratiform.digital

slack: 
  channel_url: https://stratiformworkspace.slack.com/archives/C03PPFBCLQ5

remote_theme: just-the-docs/just-the-docs
permalink: pretty
exclude: [".jekyll-cache", "node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

layout: default
nav_order: 2
has_children: true
has_toc: false

# These are all default settings.  See just-the-docs if you want to get more info.
search_enabled: true
search:
  heading_level: 2 
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "cdk-webapp on GitHub":
    - "https://github.com/stratiformdigital/cdk-webapp"
aux_links_new_tab: false

nav_sort: case_sensitive # Capital letters sorted before lowercase
# External navigation links
nav_external_links:
  - title: GitHub
    url: https://github.com/stratiformdigital/cdk-webapp
  - title: Slack
    url: https://stratiformworkspace.slack.com/archives/C03PPFBCLQ5

# Footer content; appears at the bottom of every page's main content
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy; 2022 Stratiform Digital."
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/stratiformdigital/cdk-webapp" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

color_scheme: nil # supports "dark", "light"/nil (default)

# # Google Analytics Tracking (optional)
# # e.g, UA-1234567-89
# ga_tracking: UA-2709176-10
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
