name: Create Production PR

on:
  push:
    branches: staging

jobs:
  pull-request:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: production
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: Release to production
          pr_template: .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.production.md
